#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateADGroups
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Schoolbase")]
	public partial class GetGroupDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GetGroupDataDataContext() : 
				base(global::CreateADGroups.Properties.Settings.Default.SchoolbaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GetGroupDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetGroupDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetGroupDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GetGroupDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GroupRep> GroupReps
		{
			get
			{
				return this.GetTable<GroupRep>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupRep")]
	public partial class GroupRep
	{
		
		private long _AcrIdent;
		
		private byte _AcYearIdent;
		
		private long _CurrIdent;
		
		private System.Nullable<long> _GroupIdent;
		
		private string _Subject;
		
		private string _GroupName;
		
		private string _CurricSub;
		
		private string _Mnem;
		
		private string _YearName;
		
		private string _Class;
		
		private string _FullName;
		
		private string _Mnem2;
		
		private string _Mnem3;
		
		private string _Mnem4;
		
		private System.Nullable<byte> _SV25;
		
		private string _Pu_CompNo;
		
		private string _Pu_Surname;
		
		private string _Pu_Firstname;
		
		private string _Pu_GivenName;
		
		private string _Pu_Form;
		
		private System.Nullable<bool> _Pu_Boarding;
		
		private System.Nullable<System.DateTime> _Pu_Dob;
		
		private char _Pu_Gender;
		
		private System.Nullable<System.DateTime> _Pu_Doe;
		
		private string _Pu_CandNo;
		
		private System.Nullable<int> _Pu_LastSchoolId;
		
		private System.Nullable<bool> _Pu_Schol;
		
		private string _Pu_SchDetails;
		
		private string _Pu_Info;
		
		private string _Pu_PSHouse;
		
		private System.Nullable<bool> _Pu_OFConnection;
		
		private string _Pu_Tutor;
		
		private string _PupSecondName;
		
		private string _PupThirdName;
		
		private System.Nullable<int> _PupYear;
		
		private short _BoarderIdent;
		
		private string _RelIdent;
		
		private System.Nullable<int> _GPNum;
		
		private byte _PType;
		
		private System.Nullable<byte> _StageOfProspect;
		
		private System.Nullable<System.DateTime> _PupProposedDateIn;
		
		private System.Nullable<int> _PupProposedYear;
		
		private System.Nullable<int> _PupH1;
		
		private System.Nullable<int> _PupH2;
		
		private System.Nullable<bool> _PTg1;
		
		private System.Nullable<int> _LeftToGoToCode;
		
		private string _PupLeftToGoTo;
		
		private string _PupHowHear;
		
		private System.Nullable<System.DateTime> _PupDateArchived;
		
		private char _FTime;
		
		private int _PupOrigNum;
		
		private System.Nullable<long> _YearIdent;
		
		private System.Nullable<long> _ClassIdent;
		
		private System.Nullable<int> _UserIdent;
		
		private short _PupEntScore1;
		
		private short _PupEntScore2;
		
		private short _PupEntScore3;
		
		private string _PupEntScore4;
		
		private System.Nullable<short> _PupEntScore5;
		
		private short _PupEntNum;
		
		private short _PupEntGroup;
		
		private bool _PupBurReq;
		
		private bool _PupScholReq;
		
		private string _PupIntNote;
		
		private string _PupMedNote;
		
		private int _PupForestEntIdent;
		
		private System.Nullable<short> _OfferIdent;
		
		private System.Nullable<long> _PupNewForm;
		
		private short _NatIdent;
		
		private double _PupGCSEMean;
		
		private int _PupGCSESubs;
		
		private int _PupGCSEScore;
		
		private int _PupA1Subs;
		
		private int _PupA1Score;
		
		private int _PupA2Subs;
		
		private int _PupA2Score;
		
		private string _PupAltRoll;
		
		private bool _PupInterAgree;
		
		private System.Nullable<System.DateTime> _PupAdded;
		
		private string _PupFullSurname;
		
		private string _PupTransferKey;
		
		private string _PupUCI;
		
		private string _PupUPN;
		
		private bool _PupRefTake;
		
		private System.Nullable<int> _House2Ident;
		
		private string _PupMobile;
		
		private string _PupEmail;
		
		private string _PupCohort;
		
		private byte _PupSibPos;
		
		private string _PupTransKey2;
		
		private System.Nullable<int> _TutGpIdent;
		
		private string _PupSpecial1;
		
		private string _PupSpecial2;
		
		private System.Nullable<int> _FeedAgentIdent;
		
		private System.Nullable<int> _DormIdent;
		
		private string _PupTransKey3;
		
		private string _PupReportName;
		
		private string _PupSpecial3;
		
		private System.Nullable<int> _pupWorkperson;
		
		private System.Nullable<int> _dba_stm_moodlenumber;
		
		private byte _LanIdent;
		
		private bool _PupNew;
		
		private string _PupExamName;
		
		private string _PupFeeNote;
		
		private short _EthIdent;
		
		private string _dba_stm_prevname;
		
		private string _PupNote;
		
		private double _PupSpecial4;
		
		private System.Nullable<long> _ClassIdent2;
		
		private System.DateTime _PupUpDated;
		
		private System.Nullable<System.DateTime> _PupLastExport;
		
		private short _NatIdent2;
		
		private string _PupPassNo;
		
		private string _PupPassIssuePlace;
		
		private System.Nullable<System.DateTime> _PupPassIssued;
		
		private System.Nullable<System.DateTime> _PupPassExpires;
		
		private System.Nullable<System.DateTime> _PupVisaExpires;
		
		private string _PupNHNo;
		
		private System.DateTime _PupDater;
		
		private System.Nullable<byte> _PupTempPType;
		
		private string _PupLastClass;
		
		private string _PupTransKey4;
		
		private string _PupImportName;
		
		private string _PupCare;
		
		private string _PupCareTemp;
		
		private System.Nullable<short> _HouseIdent;
		
		private System.Nullable<byte> _ShadowPType;
		
		private System.Nullable<int> _ShadowUserIdent;
		
		private System.Nullable<int> _ShadowClassIdent;
		
		private System.Nullable<int> _ShadowYearIdent;
		
		private System.Nullable<short> _ShadowHouseIdent;
		
		private System.Nullable<short> _ShadowHouse2Ident;
		
		private byte _PupXTime;
		
		private string _PupLastHouse;
		
		private string _PupLastTutor;
		
		private string _PupLastYear;
		
		private string _CentreNo;
		
		private string _PupAltUCI;
		
		private string _PupEmail2;
		
		private string _PupULN;
		
		private string _PupADSname;
		
		private System.Nullable<System.DateTime> _PupProbLeaveDate;
		
		private string _PupHashName;
		
		private string _PupPadre;
		
		private string _PupMadre;
		
		private string _PupilADName;
		
		private bool _PupShield;
		
		private string _PupVisaNo;
		
		private System.Nullable<System.DateTime> _PupVisaIssued;
		
		private string _PupVisaType;
		
		private string _PoliceRegistrationCode;
		
		private System.Nullable<int> _FinPaymentPlanIdent;
		
		private System.Nullable<short> _ShadowBoarderIdent;
		
		private bool _PupEmailExam;
		
		private bool _ExtCand;
		
		private string _PupilDisplayName;
		
		private System.Nullable<byte> _BloodTypeIdent;
		
		private System.Nullable<int> _PassportType;
		
		private string _PupEHIC;
		
		private string _PupCAS;
		
		private bool _PupDetailsChecked;
		
		private System.Nullable<int> _PupRSQtyTemp;
		
		private System.Nullable<bool> _PupMedAlert;
		
		private System.Nullable<bool> _PupSENAlert;
		
		private string _PupBoardingNotes;
		
		private bool _PupSQARegister;
		
		private string _PupFL1;
		
		private string _PupFL2;
		
		private string _PupFL3;
		
		private string _PupFL4;
		
		private string _PupFL5;
		
		private byte _AuthTypeIdent;
		
		private string _PupPassword;
		
		private string _PupInitialPassword;
		
		private byte _PupLogonLocked;
		
		private byte _PupLogonAttemptCount;
		
		private string _House;
		
		private string _Pu_House;
		
		private System.Nullable<int> _PropPType;
		
		private System.Nullable<int> _YearDesc;
		
		private string _PupNationality;
		
		private System.Nullable<int> _StaffIdent;
		
		private System.Nullable<long> _StaffIdent2;
		
		private System.Nullable<long> _StaffIdent3;
		
		private System.Nullable<long> _StaffIdent4;
		
		private string _Tutor;
		
		private string _S1;
		
		private string _S2;
		
		private string _S3;
		
		private string _S4;
		
		private string _TutMnem;
		
		private string _AgeAt;
		
		private System.Nullable<double> _AgeDec;
		
		private string _Teachers;
		
		public GroupRep()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcrIdent", DbType="BigInt NOT NULL")]
		public long AcrIdent
		{
			get
			{
				return this._AcrIdent;
			}
			set
			{
				if ((this._AcrIdent != value))
				{
					this._AcrIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcYearIdent", DbType="TinyInt NOT NULL")]
		public byte AcYearIdent
		{
			get
			{
				return this._AcYearIdent;
			}
			set
			{
				if ((this._AcYearIdent != value))
				{
					this._AcYearIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrIdent", DbType="BigInt NOT NULL")]
		public long CurrIdent
		{
			get
			{
				return this._CurrIdent;
			}
			set
			{
				if ((this._CurrIdent != value))
				{
					this._CurrIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupIdent", DbType="BigInt")]
		public System.Nullable<long> GroupIdent
		{
			get
			{
				return this._GroupIdent;
			}
			set
			{
				if ((this._GroupIdent != value))
				{
					this._GroupIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurricSub", DbType="NVarChar(50)")]
		public string CurricSub
		{
			get
			{
				return this._CurricSub;
			}
			set
			{
				if ((this._CurricSub != value))
				{
					this._CurricSub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnem", DbType="NVarChar(6)")]
		public string Mnem
		{
			get
			{
				return this._Mnem;
			}
			set
			{
				if ((this._Mnem != value))
				{
					this._Mnem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="NVarChar(50)")]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this._YearName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NVarChar(50)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnem2", DbType="NVarChar(6)")]
		public string Mnem2
		{
			get
			{
				return this._Mnem2;
			}
			set
			{
				if ((this._Mnem2 != value))
				{
					this._Mnem2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnem3", DbType="NVarChar(6)")]
		public string Mnem3
		{
			get
			{
				return this._Mnem3;
			}
			set
			{
				if ((this._Mnem3 != value))
				{
					this._Mnem3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mnem4", DbType="NVarChar(6)")]
		public string Mnem4
		{
			get
			{
				return this._Mnem4;
			}
			set
			{
				if ((this._Mnem4 != value))
				{
					this._Mnem4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV25", DbType="TinyInt")]
		public System.Nullable<byte> SV25
		{
			get
			{
				return this._SV25;
			}
			set
			{
				if ((this._SV25 != value))
				{
					this._SV25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_CompNo", DbType="NVarChar(12)")]
		public string Pu_CompNo
		{
			get
			{
				return this._Pu_CompNo;
			}
			set
			{
				if ((this._Pu_CompNo != value))
				{
					this._Pu_CompNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Surname", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Pu_Surname
		{
			get
			{
				return this._Pu_Surname;
			}
			set
			{
				if ((this._Pu_Surname != value))
				{
					this._Pu_Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Firstname", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Pu_Firstname
		{
			get
			{
				return this._Pu_Firstname;
			}
			set
			{
				if ((this._Pu_Firstname != value))
				{
					this._Pu_Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_GivenName", DbType="NVarChar(35)")]
		public string Pu_GivenName
		{
			get
			{
				return this._Pu_GivenName;
			}
			set
			{
				if ((this._Pu_GivenName != value))
				{
					this._Pu_GivenName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Form", DbType="NVarChar(4)")]
		public string Pu_Form
		{
			get
			{
				return this._Pu_Form;
			}
			set
			{
				if ((this._Pu_Form != value))
				{
					this._Pu_Form = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Boarding", DbType="Bit")]
		public System.Nullable<bool> Pu_Boarding
		{
			get
			{
				return this._Pu_Boarding;
			}
			set
			{
				if ((this._Pu_Boarding != value))
				{
					this._Pu_Boarding = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Dob", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Pu_Dob
		{
			get
			{
				return this._Pu_Dob;
			}
			set
			{
				if ((this._Pu_Dob != value))
				{
					this._Pu_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Gender", DbType="Char(1) NOT NULL")]
		public char Pu_Gender
		{
			get
			{
				return this._Pu_Gender;
			}
			set
			{
				if ((this._Pu_Gender != value))
				{
					this._Pu_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Doe", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Pu_Doe
		{
			get
			{
				return this._Pu_Doe;
			}
			set
			{
				if ((this._Pu_Doe != value))
				{
					this._Pu_Doe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_CandNo", DbType="NVarChar(4)")]
		public string Pu_CandNo
		{
			get
			{
				return this._Pu_CandNo;
			}
			set
			{
				if ((this._Pu_CandNo != value))
				{
					this._Pu_CandNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_LastSchoolId", DbType="Int")]
		public System.Nullable<int> Pu_LastSchoolId
		{
			get
			{
				return this._Pu_LastSchoolId;
			}
			set
			{
				if ((this._Pu_LastSchoolId != value))
				{
					this._Pu_LastSchoolId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Schol", DbType="Bit")]
		public System.Nullable<bool> Pu_Schol
		{
			get
			{
				return this._Pu_Schol;
			}
			set
			{
				if ((this._Pu_Schol != value))
				{
					this._Pu_Schol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_SchDetails", DbType="NVarChar(50)")]
		public string Pu_SchDetails
		{
			get
			{
				return this._Pu_SchDetails;
			}
			set
			{
				if ((this._Pu_SchDetails != value))
				{
					this._Pu_SchDetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Info", DbType="NVarChar(MAX)")]
		public string Pu_Info
		{
			get
			{
				return this._Pu_Info;
			}
			set
			{
				if ((this._Pu_Info != value))
				{
					this._Pu_Info = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_PSHouse", DbType="NVarChar(9)")]
		public string Pu_PSHouse
		{
			get
			{
				return this._Pu_PSHouse;
			}
			set
			{
				if ((this._Pu_PSHouse != value))
				{
					this._Pu_PSHouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_OFConnection", DbType="Bit")]
		public System.Nullable<bool> Pu_OFConnection
		{
			get
			{
				return this._Pu_OFConnection;
			}
			set
			{
				if ((this._Pu_OFConnection != value))
				{
					this._Pu_OFConnection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_Tutor", DbType="NVarChar(4)")]
		public string Pu_Tutor
		{
			get
			{
				return this._Pu_Tutor;
			}
			set
			{
				if ((this._Pu_Tutor != value))
				{
					this._Pu_Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSecondName", DbType="NVarChar(35)")]
		public string PupSecondName
		{
			get
			{
				return this._PupSecondName;
			}
			set
			{
				if ((this._PupSecondName != value))
				{
					this._PupSecondName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupThirdName", DbType="NVarChar(30)")]
		public string PupThirdName
		{
			get
			{
				return this._PupThirdName;
			}
			set
			{
				if ((this._PupThirdName != value))
				{
					this._PupThirdName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupYear", DbType="Int")]
		public System.Nullable<int> PupYear
		{
			get
			{
				return this._PupYear;
			}
			set
			{
				if ((this._PupYear != value))
				{
					this._PupYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoarderIdent", DbType="SmallInt NOT NULL")]
		public short BoarderIdent
		{
			get
			{
				return this._BoarderIdent;
			}
			set
			{
				if ((this._BoarderIdent != value))
				{
					this._BoarderIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelIdent", DbType="NVarChar(3)")]
		public string RelIdent
		{
			get
			{
				return this._RelIdent;
			}
			set
			{
				if ((this._RelIdent != value))
				{
					this._RelIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPNum", DbType="Int")]
		public System.Nullable<int> GPNum
		{
			get
			{
				return this._GPNum;
			}
			set
			{
				if ((this._GPNum != value))
				{
					this._GPNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PType", DbType="TinyInt NOT NULL")]
		public byte PType
		{
			get
			{
				return this._PType;
			}
			set
			{
				if ((this._PType != value))
				{
					this._PType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StageOfProspect", DbType="TinyInt")]
		public System.Nullable<byte> StageOfProspect
		{
			get
			{
				return this._StageOfProspect;
			}
			set
			{
				if ((this._StageOfProspect != value))
				{
					this._StageOfProspect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupProposedDateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupProposedDateIn
		{
			get
			{
				return this._PupProposedDateIn;
			}
			set
			{
				if ((this._PupProposedDateIn != value))
				{
					this._PupProposedDateIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupProposedYear", DbType="Int")]
		public System.Nullable<int> PupProposedYear
		{
			get
			{
				return this._PupProposedYear;
			}
			set
			{
				if ((this._PupProposedYear != value))
				{
					this._PupProposedYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupH1", DbType="Int")]
		public System.Nullable<int> PupH1
		{
			get
			{
				return this._PupH1;
			}
			set
			{
				if ((this._PupH1 != value))
				{
					this._PupH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupH2", DbType="Int")]
		public System.Nullable<int> PupH2
		{
			get
			{
				return this._PupH2;
			}
			set
			{
				if ((this._PupH2 != value))
				{
					this._PupH2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTg1", DbType="Bit")]
		public System.Nullable<bool> PTg1
		{
			get
			{
				return this._PTg1;
			}
			set
			{
				if ((this._PTg1 != value))
				{
					this._PTg1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftToGoToCode", DbType="Int")]
		public System.Nullable<int> LeftToGoToCode
		{
			get
			{
				return this._LeftToGoToCode;
			}
			set
			{
				if ((this._LeftToGoToCode != value))
				{
					this._LeftToGoToCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLeftToGoTo", DbType="NVarChar(50)")]
		public string PupLeftToGoTo
		{
			get
			{
				return this._PupLeftToGoTo;
			}
			set
			{
				if ((this._PupLeftToGoTo != value))
				{
					this._PupLeftToGoTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupHowHear", DbType="NVarChar(35)")]
		public string PupHowHear
		{
			get
			{
				return this._PupHowHear;
			}
			set
			{
				if ((this._PupHowHear != value))
				{
					this._PupHowHear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupDateArchived", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupDateArchived
		{
			get
			{
				return this._PupDateArchived;
			}
			set
			{
				if ((this._PupDateArchived != value))
				{
					this._PupDateArchived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTime", DbType="Char(1) NOT NULL")]
		public char FTime
		{
			get
			{
				return this._FTime;
			}
			set
			{
				if ((this._FTime != value))
				{
					this._FTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupOrigNum", DbType="Int NOT NULL")]
		public int PupOrigNum
		{
			get
			{
				return this._PupOrigNum;
			}
			set
			{
				if ((this._PupOrigNum != value))
				{
					this._PupOrigNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearIdent", DbType="BigInt")]
		public System.Nullable<long> YearIdent
		{
			get
			{
				return this._YearIdent;
			}
			set
			{
				if ((this._YearIdent != value))
				{
					this._YearIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassIdent", DbType="BigInt")]
		public System.Nullable<long> ClassIdent
		{
			get
			{
				return this._ClassIdent;
			}
			set
			{
				if ((this._ClassIdent != value))
				{
					this._ClassIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIdent", DbType="Int")]
		public System.Nullable<int> UserIdent
		{
			get
			{
				return this._UserIdent;
			}
			set
			{
				if ((this._UserIdent != value))
				{
					this._UserIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntScore1", DbType="SmallInt NOT NULL")]
		public short PupEntScore1
		{
			get
			{
				return this._PupEntScore1;
			}
			set
			{
				if ((this._PupEntScore1 != value))
				{
					this._PupEntScore1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntScore2", DbType="SmallInt NOT NULL")]
		public short PupEntScore2
		{
			get
			{
				return this._PupEntScore2;
			}
			set
			{
				if ((this._PupEntScore2 != value))
				{
					this._PupEntScore2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntScore3", DbType="SmallInt NOT NULL")]
		public short PupEntScore3
		{
			get
			{
				return this._PupEntScore3;
			}
			set
			{
				if ((this._PupEntScore3 != value))
				{
					this._PupEntScore3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntScore4", DbType="NVarChar(8)")]
		public string PupEntScore4
		{
			get
			{
				return this._PupEntScore4;
			}
			set
			{
				if ((this._PupEntScore4 != value))
				{
					this._PupEntScore4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntScore5", DbType="SmallInt")]
		public System.Nullable<short> PupEntScore5
		{
			get
			{
				return this._PupEntScore5;
			}
			set
			{
				if ((this._PupEntScore5 != value))
				{
					this._PupEntScore5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntNum", DbType="SmallInt NOT NULL")]
		public short PupEntNum
		{
			get
			{
				return this._PupEntNum;
			}
			set
			{
				if ((this._PupEntNum != value))
				{
					this._PupEntNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEntGroup", DbType="SmallInt NOT NULL")]
		public short PupEntGroup
		{
			get
			{
				return this._PupEntGroup;
			}
			set
			{
				if ((this._PupEntGroup != value))
				{
					this._PupEntGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupBurReq", DbType="Bit NOT NULL")]
		public bool PupBurReq
		{
			get
			{
				return this._PupBurReq;
			}
			set
			{
				if ((this._PupBurReq != value))
				{
					this._PupBurReq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupScholReq", DbType="Bit NOT NULL")]
		public bool PupScholReq
		{
			get
			{
				return this._PupScholReq;
			}
			set
			{
				if ((this._PupScholReq != value))
				{
					this._PupScholReq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupIntNote", DbType="NVarChar(MAX)")]
		public string PupIntNote
		{
			get
			{
				return this._PupIntNote;
			}
			set
			{
				if ((this._PupIntNote != value))
				{
					this._PupIntNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupMedNote", DbType="NVarChar(MAX)")]
		public string PupMedNote
		{
			get
			{
				return this._PupMedNote;
			}
			set
			{
				if ((this._PupMedNote != value))
				{
					this._PupMedNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupForestEntIdent", DbType="Int NOT NULL")]
		public int PupForestEntIdent
		{
			get
			{
				return this._PupForestEntIdent;
			}
			set
			{
				if ((this._PupForestEntIdent != value))
				{
					this._PupForestEntIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfferIdent", DbType="SmallInt")]
		public System.Nullable<short> OfferIdent
		{
			get
			{
				return this._OfferIdent;
			}
			set
			{
				if ((this._OfferIdent != value))
				{
					this._OfferIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupNewForm", DbType="BigInt")]
		public System.Nullable<long> PupNewForm
		{
			get
			{
				return this._PupNewForm;
			}
			set
			{
				if ((this._PupNewForm != value))
				{
					this._PupNewForm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NatIdent", DbType="SmallInt NOT NULL")]
		public short NatIdent
		{
			get
			{
				return this._NatIdent;
			}
			set
			{
				if ((this._NatIdent != value))
				{
					this._NatIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupGCSEMean", DbType="Float NOT NULL")]
		public double PupGCSEMean
		{
			get
			{
				return this._PupGCSEMean;
			}
			set
			{
				if ((this._PupGCSEMean != value))
				{
					this._PupGCSEMean = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupGCSESubs", DbType="Int NOT NULL")]
		public int PupGCSESubs
		{
			get
			{
				return this._PupGCSESubs;
			}
			set
			{
				if ((this._PupGCSESubs != value))
				{
					this._PupGCSESubs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupGCSEScore", DbType="Int NOT NULL")]
		public int PupGCSEScore
		{
			get
			{
				return this._PupGCSEScore;
			}
			set
			{
				if ((this._PupGCSEScore != value))
				{
					this._PupGCSEScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupA1Subs", DbType="Int NOT NULL")]
		public int PupA1Subs
		{
			get
			{
				return this._PupA1Subs;
			}
			set
			{
				if ((this._PupA1Subs != value))
				{
					this._PupA1Subs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupA1Score", DbType="Int NOT NULL")]
		public int PupA1Score
		{
			get
			{
				return this._PupA1Score;
			}
			set
			{
				if ((this._PupA1Score != value))
				{
					this._PupA1Score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupA2Subs", DbType="Int NOT NULL")]
		public int PupA2Subs
		{
			get
			{
				return this._PupA2Subs;
			}
			set
			{
				if ((this._PupA2Subs != value))
				{
					this._PupA2Subs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupA2Score", DbType="Int NOT NULL")]
		public int PupA2Score
		{
			get
			{
				return this._PupA2Score;
			}
			set
			{
				if ((this._PupA2Score != value))
				{
					this._PupA2Score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupAltRoll", DbType="NVarChar(6)")]
		public string PupAltRoll
		{
			get
			{
				return this._PupAltRoll;
			}
			set
			{
				if ((this._PupAltRoll != value))
				{
					this._PupAltRoll = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupInterAgree", DbType="Bit NOT NULL")]
		public bool PupInterAgree
		{
			get
			{
				return this._PupInterAgree;
			}
			set
			{
				if ((this._PupInterAgree != value))
				{
					this._PupInterAgree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupAdded
		{
			get
			{
				return this._PupAdded;
			}
			set
			{
				if ((this._PupAdded != value))
				{
					this._PupAdded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFullSurname", DbType="NVarChar(30)")]
		public string PupFullSurname
		{
			get
			{
				return this._PupFullSurname;
			}
			set
			{
				if ((this._PupFullSurname != value))
				{
					this._PupFullSurname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupTransferKey", DbType="NVarChar(20)")]
		public string PupTransferKey
		{
			get
			{
				return this._PupTransferKey;
			}
			set
			{
				if ((this._PupTransferKey != value))
				{
					this._PupTransferKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupUCI", DbType="NVarChar(13)")]
		public string PupUCI
		{
			get
			{
				return this._PupUCI;
			}
			set
			{
				if ((this._PupUCI != value))
				{
					this._PupUCI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupUPN", DbType="NVarChar(13)")]
		public string PupUPN
		{
			get
			{
				return this._PupUPN;
			}
			set
			{
				if ((this._PupUPN != value))
				{
					this._PupUPN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupRefTake", DbType="Bit NOT NULL")]
		public bool PupRefTake
		{
			get
			{
				return this._PupRefTake;
			}
			set
			{
				if ((this._PupRefTake != value))
				{
					this._PupRefTake = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_House2Ident", DbType="Int")]
		public System.Nullable<int> House2Ident
		{
			get
			{
				return this._House2Ident;
			}
			set
			{
				if ((this._House2Ident != value))
				{
					this._House2Ident = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupMobile", DbType="NVarChar(20)")]
		public string PupMobile
		{
			get
			{
				return this._PupMobile;
			}
			set
			{
				if ((this._PupMobile != value))
				{
					this._PupMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEmail", DbType="NVarChar(50)")]
		public string PupEmail
		{
			get
			{
				return this._PupEmail;
			}
			set
			{
				if ((this._PupEmail != value))
				{
					this._PupEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupCohort", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string PupCohort
		{
			get
			{
				return this._PupCohort;
			}
			set
			{
				if ((this._PupCohort != value))
				{
					this._PupCohort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSibPos", DbType="TinyInt NOT NULL")]
		public byte PupSibPos
		{
			get
			{
				return this._PupSibPos;
			}
			set
			{
				if ((this._PupSibPos != value))
				{
					this._PupSibPos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupTransKey2", DbType="NVarChar(20)")]
		public string PupTransKey2
		{
			get
			{
				return this._PupTransKey2;
			}
			set
			{
				if ((this._PupTransKey2 != value))
				{
					this._PupTransKey2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TutGpIdent", DbType="Int")]
		public System.Nullable<int> TutGpIdent
		{
			get
			{
				return this._TutGpIdent;
			}
			set
			{
				if ((this._TutGpIdent != value))
				{
					this._TutGpIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSpecial1", DbType="NVarChar(50)")]
		public string PupSpecial1
		{
			get
			{
				return this._PupSpecial1;
			}
			set
			{
				if ((this._PupSpecial1 != value))
				{
					this._PupSpecial1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSpecial2", DbType="NVarChar(50)")]
		public string PupSpecial2
		{
			get
			{
				return this._PupSpecial2;
			}
			set
			{
				if ((this._PupSpecial2 != value))
				{
					this._PupSpecial2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedAgentIdent", DbType="Int")]
		public System.Nullable<int> FeedAgentIdent
		{
			get
			{
				return this._FeedAgentIdent;
			}
			set
			{
				if ((this._FeedAgentIdent != value))
				{
					this._FeedAgentIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DormIdent", DbType="Int")]
		public System.Nullable<int> DormIdent
		{
			get
			{
				return this._DormIdent;
			}
			set
			{
				if ((this._DormIdent != value))
				{
					this._DormIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupTransKey3", DbType="NVarChar(20)")]
		public string PupTransKey3
		{
			get
			{
				return this._PupTransKey3;
			}
			set
			{
				if ((this._PupTransKey3 != value))
				{
					this._PupTransKey3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupReportName", DbType="NVarChar(60)")]
		public string PupReportName
		{
			get
			{
				return this._PupReportName;
			}
			set
			{
				if ((this._PupReportName != value))
				{
					this._PupReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSpecial3", DbType="NVarChar(50)")]
		public string PupSpecial3
		{
			get
			{
				return this._PupSpecial3;
			}
			set
			{
				if ((this._PupSpecial3 != value))
				{
					this._PupSpecial3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pupWorkperson", DbType="Int")]
		public System.Nullable<int> pupWorkperson
		{
			get
			{
				return this._pupWorkperson;
			}
			set
			{
				if ((this._pupWorkperson != value))
				{
					this._pupWorkperson = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dba_stm_moodlenumber", DbType="Int")]
		public System.Nullable<int> dba_stm_moodlenumber
		{
			get
			{
				return this._dba_stm_moodlenumber;
			}
			set
			{
				if ((this._dba_stm_moodlenumber != value))
				{
					this._dba_stm_moodlenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanIdent", DbType="TinyInt NOT NULL")]
		public byte LanIdent
		{
			get
			{
				return this._LanIdent;
			}
			set
			{
				if ((this._LanIdent != value))
				{
					this._LanIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupNew", DbType="Bit NOT NULL")]
		public bool PupNew
		{
			get
			{
				return this._PupNew;
			}
			set
			{
				if ((this._PupNew != value))
				{
					this._PupNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupExamName", DbType="NVarChar(80)")]
		public string PupExamName
		{
			get
			{
				return this._PupExamName;
			}
			set
			{
				if ((this._PupExamName != value))
				{
					this._PupExamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFeeNote", DbType="NVarChar(255)")]
		public string PupFeeNote
		{
			get
			{
				return this._PupFeeNote;
			}
			set
			{
				if ((this._PupFeeNote != value))
				{
					this._PupFeeNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EthIdent", DbType="SmallInt NOT NULL")]
		public short EthIdent
		{
			get
			{
				return this._EthIdent;
			}
			set
			{
				if ((this._EthIdent != value))
				{
					this._EthIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dba_stm_prevname", DbType="NVarChar(30)")]
		public string dba_stm_prevname
		{
			get
			{
				return this._dba_stm_prevname;
			}
			set
			{
				if ((this._dba_stm_prevname != value))
				{
					this._dba_stm_prevname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupNote", DbType="NVarChar(MAX)")]
		public string PupNote
		{
			get
			{
				return this._PupNote;
			}
			set
			{
				if ((this._PupNote != value))
				{
					this._PupNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSpecial4", DbType="Float NOT NULL")]
		public double PupSpecial4
		{
			get
			{
				return this._PupSpecial4;
			}
			set
			{
				if ((this._PupSpecial4 != value))
				{
					this._PupSpecial4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassIdent2", DbType="BigInt")]
		public System.Nullable<long> ClassIdent2
		{
			get
			{
				return this._ClassIdent2;
			}
			set
			{
				if ((this._ClassIdent2 != value))
				{
					this._ClassIdent2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupUpDated", DbType="DateTime NOT NULL")]
		public System.DateTime PupUpDated
		{
			get
			{
				return this._PupUpDated;
			}
			set
			{
				if ((this._PupUpDated != value))
				{
					this._PupUpDated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLastExport", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupLastExport
		{
			get
			{
				return this._PupLastExport;
			}
			set
			{
				if ((this._PupLastExport != value))
				{
					this._PupLastExport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NatIdent2", DbType="SmallInt NOT NULL")]
		public short NatIdent2
		{
			get
			{
				return this._NatIdent2;
			}
			set
			{
				if ((this._NatIdent2 != value))
				{
					this._NatIdent2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPassNo", DbType="NVarChar(20)")]
		public string PupPassNo
		{
			get
			{
				return this._PupPassNo;
			}
			set
			{
				if ((this._PupPassNo != value))
				{
					this._PupPassNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPassIssuePlace", DbType="NVarChar(20)")]
		public string PupPassIssuePlace
		{
			get
			{
				return this._PupPassIssuePlace;
			}
			set
			{
				if ((this._PupPassIssuePlace != value))
				{
					this._PupPassIssuePlace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPassIssued", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupPassIssued
		{
			get
			{
				return this._PupPassIssued;
			}
			set
			{
				if ((this._PupPassIssued != value))
				{
					this._PupPassIssued = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPassExpires", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupPassExpires
		{
			get
			{
				return this._PupPassExpires;
			}
			set
			{
				if ((this._PupPassExpires != value))
				{
					this._PupPassExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupVisaExpires", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupVisaExpires
		{
			get
			{
				return this._PupVisaExpires;
			}
			set
			{
				if ((this._PupVisaExpires != value))
				{
					this._PupVisaExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupNHNo", DbType="NVarChar(15)")]
		public string PupNHNo
		{
			get
			{
				return this._PupNHNo;
			}
			set
			{
				if ((this._PupNHNo != value))
				{
					this._PupNHNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupDater", DbType="DateTime NOT NULL")]
		public System.DateTime PupDater
		{
			get
			{
				return this._PupDater;
			}
			set
			{
				if ((this._PupDater != value))
				{
					this._PupDater = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupTempPType", DbType="TinyInt")]
		public System.Nullable<byte> PupTempPType
		{
			get
			{
				return this._PupTempPType;
			}
			set
			{
				if ((this._PupTempPType != value))
				{
					this._PupTempPType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLastClass", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PupLastClass
		{
			get
			{
				return this._PupLastClass;
			}
			set
			{
				if ((this._PupLastClass != value))
				{
					this._PupLastClass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupTransKey4", DbType="NVarChar(20)")]
		public string PupTransKey4
		{
			get
			{
				return this._PupTransKey4;
			}
			set
			{
				if ((this._PupTransKey4 != value))
				{
					this._PupTransKey4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupImportName", DbType="NVarChar(60)")]
		public string PupImportName
		{
			get
			{
				return this._PupImportName;
			}
			set
			{
				if ((this._PupImportName != value))
				{
					this._PupImportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupCare", DbType="NVarChar(10)")]
		public string PupCare
		{
			get
			{
				return this._PupCare;
			}
			set
			{
				if ((this._PupCare != value))
				{
					this._PupCare = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupCareTemp", DbType="NVarChar(10)")]
		public string PupCareTemp
		{
			get
			{
				return this._PupCareTemp;
			}
			set
			{
				if ((this._PupCareTemp != value))
				{
					this._PupCareTemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseIdent", DbType="SmallInt")]
		public System.Nullable<short> HouseIdent
		{
			get
			{
				return this._HouseIdent;
			}
			set
			{
				if ((this._HouseIdent != value))
				{
					this._HouseIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowPType", DbType="TinyInt")]
		public System.Nullable<byte> ShadowPType
		{
			get
			{
				return this._ShadowPType;
			}
			set
			{
				if ((this._ShadowPType != value))
				{
					this._ShadowPType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowUserIdent", DbType="Int")]
		public System.Nullable<int> ShadowUserIdent
		{
			get
			{
				return this._ShadowUserIdent;
			}
			set
			{
				if ((this._ShadowUserIdent != value))
				{
					this._ShadowUserIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowClassIdent", DbType="Int")]
		public System.Nullable<int> ShadowClassIdent
		{
			get
			{
				return this._ShadowClassIdent;
			}
			set
			{
				if ((this._ShadowClassIdent != value))
				{
					this._ShadowClassIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowYearIdent", DbType="Int")]
		public System.Nullable<int> ShadowYearIdent
		{
			get
			{
				return this._ShadowYearIdent;
			}
			set
			{
				if ((this._ShadowYearIdent != value))
				{
					this._ShadowYearIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowHouseIdent", DbType="SmallInt")]
		public System.Nullable<short> ShadowHouseIdent
		{
			get
			{
				return this._ShadowHouseIdent;
			}
			set
			{
				if ((this._ShadowHouseIdent != value))
				{
					this._ShadowHouseIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowHouse2Ident", DbType="SmallInt")]
		public System.Nullable<short> ShadowHouse2Ident
		{
			get
			{
				return this._ShadowHouse2Ident;
			}
			set
			{
				if ((this._ShadowHouse2Ident != value))
				{
					this._ShadowHouse2Ident = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupXTime", DbType="TinyInt NOT NULL")]
		public byte PupXTime
		{
			get
			{
				return this._PupXTime;
			}
			set
			{
				if ((this._PupXTime != value))
				{
					this._PupXTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLastHouse", DbType="NVarChar(20)")]
		public string PupLastHouse
		{
			get
			{
				return this._PupLastHouse;
			}
			set
			{
				if ((this._PupLastHouse != value))
				{
					this._PupLastHouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLastTutor", DbType="NVarChar(10)")]
		public string PupLastTutor
		{
			get
			{
				return this._PupLastTutor;
			}
			set
			{
				if ((this._PupLastTutor != value))
				{
					this._PupLastTutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLastYear", DbType="NVarChar(20)")]
		public string PupLastYear
		{
			get
			{
				return this._PupLastYear;
			}
			set
			{
				if ((this._PupLastYear != value))
				{
					this._PupLastYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentreNo", DbType="NVarChar(7)")]
		public string CentreNo
		{
			get
			{
				return this._CentreNo;
			}
			set
			{
				if ((this._CentreNo != value))
				{
					this._CentreNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupAltUCI", DbType="NVarChar(13)")]
		public string PupAltUCI
		{
			get
			{
				return this._PupAltUCI;
			}
			set
			{
				if ((this._PupAltUCI != value))
				{
					this._PupAltUCI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEmail2", DbType="NVarChar(50)")]
		public string PupEmail2
		{
			get
			{
				return this._PupEmail2;
			}
			set
			{
				if ((this._PupEmail2 != value))
				{
					this._PupEmail2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupULN", DbType="Char(10)")]
		public string PupULN
		{
			get
			{
				return this._PupULN;
			}
			set
			{
				if ((this._PupULN != value))
				{
					this._PupULN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupADSname", DbType="NVarChar(100)")]
		public string PupADSname
		{
			get
			{
				return this._PupADSname;
			}
			set
			{
				if ((this._PupADSname != value))
				{
					this._PupADSname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupProbLeaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupProbLeaveDate
		{
			get
			{
				return this._PupProbLeaveDate;
			}
			set
			{
				if ((this._PupProbLeaveDate != value))
				{
					this._PupProbLeaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupHashName", DbType="NVarChar(35)")]
		public string PupHashName
		{
			get
			{
				return this._PupHashName;
			}
			set
			{
				if ((this._PupHashName != value))
				{
					this._PupHashName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPadre", DbType="NVarChar(30)")]
		public string PupPadre
		{
			get
			{
				return this._PupPadre;
			}
			set
			{
				if ((this._PupPadre != value))
				{
					this._PupPadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupMadre", DbType="NVarChar(30)")]
		public string PupMadre
		{
			get
			{
				return this._PupMadre;
			}
			set
			{
				if ((this._PupMadre != value))
				{
					this._PupMadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupilADName", DbType="NVarChar(30)")]
		public string PupilADName
		{
			get
			{
				return this._PupilADName;
			}
			set
			{
				if ((this._PupilADName != value))
				{
					this._PupilADName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupShield", DbType="Bit NOT NULL")]
		public bool PupShield
		{
			get
			{
				return this._PupShield;
			}
			set
			{
				if ((this._PupShield != value))
				{
					this._PupShield = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupVisaNo", DbType="NVarChar(20)")]
		public string PupVisaNo
		{
			get
			{
				return this._PupVisaNo;
			}
			set
			{
				if ((this._PupVisaNo != value))
				{
					this._PupVisaNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupVisaIssued", DbType="DateTime")]
		public System.Nullable<System.DateTime> PupVisaIssued
		{
			get
			{
				return this._PupVisaIssued;
			}
			set
			{
				if ((this._PupVisaIssued != value))
				{
					this._PupVisaIssued = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupVisaType", DbType="NVarChar(20)")]
		public string PupVisaType
		{
			get
			{
				return this._PupVisaType;
			}
			set
			{
				if ((this._PupVisaType != value))
				{
					this._PupVisaType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliceRegistrationCode", DbType="NVarChar(20)")]
		public string PoliceRegistrationCode
		{
			get
			{
				return this._PoliceRegistrationCode;
			}
			set
			{
				if ((this._PoliceRegistrationCode != value))
				{
					this._PoliceRegistrationCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinPaymentPlanIdent", DbType="Int")]
		public System.Nullable<int> FinPaymentPlanIdent
		{
			get
			{
				return this._FinPaymentPlanIdent;
			}
			set
			{
				if ((this._FinPaymentPlanIdent != value))
				{
					this._FinPaymentPlanIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShadowBoarderIdent", DbType="SmallInt")]
		public System.Nullable<short> ShadowBoarderIdent
		{
			get
			{
				return this._ShadowBoarderIdent;
			}
			set
			{
				if ((this._ShadowBoarderIdent != value))
				{
					this._ShadowBoarderIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEmailExam", DbType="Bit NOT NULL")]
		public bool PupEmailExam
		{
			get
			{
				return this._PupEmailExam;
			}
			set
			{
				if ((this._PupEmailExam != value))
				{
					this._PupEmailExam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtCand", DbType="Bit NOT NULL")]
		public bool ExtCand
		{
			get
			{
				return this._ExtCand;
			}
			set
			{
				if ((this._ExtCand != value))
				{
					this._ExtCand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupilDisplayName", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string PupilDisplayName
		{
			get
			{
				return this._PupilDisplayName;
			}
			set
			{
				if ((this._PupilDisplayName != value))
				{
					this._PupilDisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodTypeIdent", DbType="TinyInt")]
		public System.Nullable<byte> BloodTypeIdent
		{
			get
			{
				return this._BloodTypeIdent;
			}
			set
			{
				if ((this._BloodTypeIdent != value))
				{
					this._BloodTypeIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportType", DbType="Int")]
		public System.Nullable<int> PassportType
		{
			get
			{
				return this._PassportType;
			}
			set
			{
				if ((this._PassportType != value))
				{
					this._PassportType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupEHIC", DbType="NVarChar(30)")]
		public string PupEHIC
		{
			get
			{
				return this._PupEHIC;
			}
			set
			{
				if ((this._PupEHIC != value))
				{
					this._PupEHIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupCAS", DbType="NVarChar(15)")]
		public string PupCAS
		{
			get
			{
				return this._PupCAS;
			}
			set
			{
				if ((this._PupCAS != value))
				{
					this._PupCAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupDetailsChecked", DbType="Bit NOT NULL")]
		public bool PupDetailsChecked
		{
			get
			{
				return this._PupDetailsChecked;
			}
			set
			{
				if ((this._PupDetailsChecked != value))
				{
					this._PupDetailsChecked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupRSQtyTemp", DbType="Int")]
		public System.Nullable<int> PupRSQtyTemp
		{
			get
			{
				return this._PupRSQtyTemp;
			}
			set
			{
				if ((this._PupRSQtyTemp != value))
				{
					this._PupRSQtyTemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupMedAlert", DbType="Bit")]
		public System.Nullable<bool> PupMedAlert
		{
			get
			{
				return this._PupMedAlert;
			}
			set
			{
				if ((this._PupMedAlert != value))
				{
					this._PupMedAlert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSENAlert", DbType="Bit")]
		public System.Nullable<bool> PupSENAlert
		{
			get
			{
				return this._PupSENAlert;
			}
			set
			{
				if ((this._PupSENAlert != value))
				{
					this._PupSENAlert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupBoardingNotes", DbType="NVarChar(MAX)")]
		public string PupBoardingNotes
		{
			get
			{
				return this._PupBoardingNotes;
			}
			set
			{
				if ((this._PupBoardingNotes != value))
				{
					this._PupBoardingNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupSQARegister", DbType="Bit NOT NULL")]
		public bool PupSQARegister
		{
			get
			{
				return this._PupSQARegister;
			}
			set
			{
				if ((this._PupSQARegister != value))
				{
					this._PupSQARegister = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFL1", DbType="NVarChar(25)")]
		public string PupFL1
		{
			get
			{
				return this._PupFL1;
			}
			set
			{
				if ((this._PupFL1 != value))
				{
					this._PupFL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFL2", DbType="NVarChar(35)")]
		public string PupFL2
		{
			get
			{
				return this._PupFL2;
			}
			set
			{
				if ((this._PupFL2 != value))
				{
					this._PupFL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFL3", DbType="NVarChar(35)")]
		public string PupFL3
		{
			get
			{
				return this._PupFL3;
			}
			set
			{
				if ((this._PupFL3 != value))
				{
					this._PupFL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFL4", DbType="NVarChar(20)")]
		public string PupFL4
		{
			get
			{
				return this._PupFL4;
			}
			set
			{
				if ((this._PupFL4 != value))
				{
					this._PupFL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupFL5", DbType="NVarChar(30)")]
		public string PupFL5
		{
			get
			{
				return this._PupFL5;
			}
			set
			{
				if ((this._PupFL5 != value))
				{
					this._PupFL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthTypeIdent", DbType="TinyInt NOT NULL")]
		public byte AuthTypeIdent
		{
			get
			{
				return this._AuthTypeIdent;
			}
			set
			{
				if ((this._AuthTypeIdent != value))
				{
					this._AuthTypeIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupPassword", DbType="NVarChar(100)")]
		public string PupPassword
		{
			get
			{
				return this._PupPassword;
			}
			set
			{
				if ((this._PupPassword != value))
				{
					this._PupPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupInitialPassword", DbType="NVarChar(100)")]
		public string PupInitialPassword
		{
			get
			{
				return this._PupInitialPassword;
			}
			set
			{
				if ((this._PupInitialPassword != value))
				{
					this._PupInitialPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLogonLocked", DbType="TinyInt NOT NULL")]
		public byte PupLogonLocked
		{
			get
			{
				return this._PupLogonLocked;
			}
			set
			{
				if ((this._PupLogonLocked != value))
				{
					this._PupLogonLocked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupLogonAttemptCount", DbType="TinyInt NOT NULL")]
		public byte PupLogonAttemptCount
		{
			get
			{
				return this._PupLogonAttemptCount;
			}
			set
			{
				if ((this._PupLogonAttemptCount != value))
				{
					this._PupLogonAttemptCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_House", DbType="NVarChar(9)")]
		public string House
		{
			get
			{
				return this._House;
			}
			set
			{
				if ((this._House != value))
				{
					this._House = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pu_House", DbType="NVarChar(9)")]
		public string Pu_House
		{
			get
			{
				return this._Pu_House;
			}
			set
			{
				if ((this._Pu_House != value))
				{
					this._Pu_House = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropPType", DbType="Int")]
		public System.Nullable<int> PropPType
		{
			get
			{
				return this._PropPType;
			}
			set
			{
				if ((this._PropPType != value))
				{
					this._PropPType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearDesc", DbType="Int")]
		public System.Nullable<int> YearDesc
		{
			get
			{
				return this._YearDesc;
			}
			set
			{
				if ((this._YearDesc != value))
				{
					this._YearDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PupNationality", DbType="NVarChar(50)")]
		public string PupNationality
		{
			get
			{
				return this._PupNationality;
			}
			set
			{
				if ((this._PupNationality != value))
				{
					this._PupNationality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffIdent", DbType="Int")]
		public System.Nullable<int> StaffIdent
		{
			get
			{
				return this._StaffIdent;
			}
			set
			{
				if ((this._StaffIdent != value))
				{
					this._StaffIdent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffIdent2", DbType="BigInt")]
		public System.Nullable<long> StaffIdent2
		{
			get
			{
				return this._StaffIdent2;
			}
			set
			{
				if ((this._StaffIdent2 != value))
				{
					this._StaffIdent2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffIdent3", DbType="BigInt")]
		public System.Nullable<long> StaffIdent3
		{
			get
			{
				return this._StaffIdent3;
			}
			set
			{
				if ((this._StaffIdent3 != value))
				{
					this._StaffIdent3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffIdent4", DbType="BigInt")]
		public System.Nullable<long> StaffIdent4
		{
			get
			{
				return this._StaffIdent4;
			}
			set
			{
				if ((this._StaffIdent4 != value))
				{
					this._StaffIdent4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutor", DbType="NVarChar(50)")]
		public string Tutor
		{
			get
			{
				return this._Tutor;
			}
			set
			{
				if ((this._Tutor != value))
				{
					this._Tutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S1", DbType="NVarChar(50)")]
		public string S1
		{
			get
			{
				return this._S1;
			}
			set
			{
				if ((this._S1 != value))
				{
					this._S1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S2", DbType="NVarChar(50)")]
		public string S2
		{
			get
			{
				return this._S2;
			}
			set
			{
				if ((this._S2 != value))
				{
					this._S2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3", DbType="NVarChar(50)")]
		public string S3
		{
			get
			{
				return this._S3;
			}
			set
			{
				if ((this._S3 != value))
				{
					this._S3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S4", DbType="NVarChar(50)")]
		public string S4
		{
			get
			{
				return this._S4;
			}
			set
			{
				if ((this._S4 != value))
				{
					this._S4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TutMnem", DbType="NVarChar(6)")]
		public string TutMnem
		{
			get
			{
				return this._TutMnem;
			}
			set
			{
				if ((this._TutMnem != value))
				{
					this._TutMnem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeAt", DbType="NVarChar(20)")]
		public string AgeAt
		{
			get
			{
				return this._AgeAt;
			}
			set
			{
				if ((this._AgeAt != value))
				{
					this._AgeAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeDec", DbType="Float")]
		public System.Nullable<double> AgeDec
		{
			get
			{
				return this._AgeDec;
			}
			set
			{
				if ((this._AgeDec != value))
				{
					this._AgeDec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teachers", DbType="NVarChar(4000)")]
		public string Teachers
		{
			get
			{
				return this._Teachers;
			}
			set
			{
				if ((this._Teachers != value))
				{
					this._Teachers = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
